node {
    stage('checkout') {
        checkout([
        $class: 'GitSCM',
        branches: [[name: '*/main']],
        userRemoteConfigs: [[
            credentialsId: 'jenkins-github',
            url: 'https://github.com/Eliseev-Max/warehouse_tests.git'
            ]]
        ])
    }
    stage('build_image') {
        sh 'docker build -t wh_tests .'
    }
    stage('test') {
        sh """
            docker run -v $WORKSPACE/allure-results/:/app/allure-results wh_tests:latest
        """
    }
    stage('report-allure') {
        allure([
            includeProperties: false,
            jdk: '',
            properties: [],
            reportBuildPolicy: 'ALWAYS',
            results: [[path: '$WORKSPACE/allure-results']]
        ])
    }
}


pipeline {
	agent none
	
	stages {
		stage('BuildDockerImage') {
			steps {
				agent dockerfile {
					additionalBuildArgs '-t wh_tests'
				}
			}
		}
		stage('RunContainerWithTests') {
			steps {
				agent docker {
					image ''
					args '-v $WORKSPACE/allure-results/:/app/allure-results'
				}
			}
		}
		stage('allure-report') {
			steps {
				agent any {
				script {
                    allure([
                        includeProperties: false,
						jdk: '',
						properties: [],
						reportBuildPolicy: 'ALWAYS',
						results: [[path: '$WORKSPACE/allure-results']]
                    ])
                }
					
				}
			}
		}
	}
}
