apiVersion: v1
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m
    route:
       group_wait: 10s
       group_interval: 30s
       repeat_interval: 30m
       receiver: "telegram"
       routes:
         - receiver: "telegram"
           group_wait: 10s
           match_re:
             severity: critical|warning
           continue: true
    receivers:
     - name: "telegram"
       telegram_configs:
         - send_resolved: true
           bot_token: "5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs"
           chat_id: -1.002065700118e+12
           api_url: "https://api.telegram.org"
           message: "Alertmanager (std-017-033) \n  Alertname: {{ .GroupLabels.alertname }} \n Severity: {{ .CommonLabels.severity }}\n  {{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: alertmanager
    meta.helm.sh/release-namespace: std-017-033
  creationTimestamp: "2024-12-26T15:33:18Z"
  labels:
    app: alertmanager
    app.kubernetes.io/managed-by: Helm
  name: alertmanager
  namespace: std-017-033
  resourceVersion: "2309788711"
  uid: d6d347f9-56b6-4da8-a822-77e93eb23839
